### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by popey** [snapcrafters/axel#2]
`Failed to fetch stage packages: Error downloading packages for part 'axel': The package 'libssl1.1' was not found..`

From the latest [build log](https://launchpadlibrarian.net/372962063/buildlog_snap_ubuntu_xenial_amd64_1c7edf66b8a27bd4ca35886b0511f15e-xenial_BUILDING.txt.gz)

@om26er ^

**Comment by om26er** [comment]
@popey thanks for the report, I proposed a fix here https://github.com/snapcrafters/axel/pull/3
