### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by abcfy2** [snapcrafters/axel#6]
```bash
sudo snap install axel
axel https://github.com
Initializing download: https://github.com
Unable to connect to server github.com:443: Temporary failure in name resolution
```

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting! This actually seems like a network issue in your side. Do you still have this issue with the latest version? If so, can you let us know what OS and `snapd` version you're working on?
